version: '3'

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: timehollyname/foodgram:1.0
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --chdir ./project
    volumes:
      - static:/FoodGram/project/static/
      - media:/FoodGram/project/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - web

volumes:
  postgres:
  static:
  media: